[build]
compiler = "gcc"
# fill in your app path
app = "./rootfs/perl"

[os]
name = "ruxos"
services = ["paging","alloc","irq","multitask","fs","pipe","poll","rtc","signal","virtio-9p"]
ulib = "ruxmusl"

[os.platform]
name = "aarch64-qemu-virt"
smp = "1"
log = "info"

[os.platform.qemu]
memory = "256M"
v9p = "y"
v9p_path = "./rootfs"
# your app parameter config
args = "perl,your_perl.t"
